# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

r1 = Restaurant.create(name: "Ophelia's Electric Soapbox", phone_number: 3039938023, address: '1215 20th Street, Denver CO', yelp_review_link: 'https://www.yelp.com/biz/ophelias-electric-soapbox-denver')
r2 = Restaurant.create(name: "Elway's", phone_number: 3033123107, address: '1881 Curtis St, Denver', yelp_review_link: 'https://www.yelp.com/biz/elways-denver-5')
r3 = Restaurant.create(name: "Ignite Kitchen + Cocktails", phone_number: 3032962600, address: '2124 Larimer St, Denver, CO', yelp_review_link: 'https://www.yelp.com/biz/ignite-kitchen-cocktails-denver')
r4 = Restaurant.create(name: "Mexico City Restaurant & Lounge", phone_number: 3032960563, address: '2115 Larimer St, Denver, CO', yelp_review_link: 'https://www.yelp.com/biz/mexico-city-restaurant-and-lounge-denver')
r5 = Restaurant.create(name: "The Palm Denver", phone_number: 3038257256, address: "1672 Lawrence St, Denver, CO", yelp_review_link: 'https://www.yelp.com/biz/the-palm-denver-denver')
r6 = Restaurant.create(name: "Vesta", phone_number: 3032961970, address: "1822 Blake St, Denver CO", yelp_review_link: 'https://www.yelp.com/biz/vesta-denver')
r7 = Restaurant.create(name: "Mici Handcrafted Italian", phone_number: 3036296424, address: '1531 Stout St, Denver CO', yelp_review_link: 'https://www.yelp.com/biz/mici-handcrafted-italian-denver-9')
r8 = Restaurant.create(name: "Rioja", phone_number: 3038202282, address: '1431 Larimer St, Denver CO', yelp_review_link: 'https://www.yelp.com/biz/rioja-denver')
r9 = Restaurant.create(name: "Work & Class", phone_number: 3032920700, address: '2500 Larimer St, Denver CO', yelp_review_link: 'https://www.yelp.com/biz/work-and-class-denver')
r10 = Restaurant.create(name: "Biker Jim's Gourmet Dogs", phone_number: 7207469355, address: '2148 Larimer St, Denver CO', yelp_review_link: 'https://www.yelp.com/biz/biker-jim-s-gourmet-dogs-denver')

Tag.create(type: 'Greek')
Tag.create(type: 'French')
Tag.create(type: 'American')
Tag.create(type: 'Asian')
Tag.create(type: 'Venezuelan')
Tag.create(type: 'Craft Beer')
Tag.create(type: 'Steakhouse')
Tag.create(type: 'Gluten Free')
Tag.create(type: 'Burgers')
Tag.create(type: 'Seafood')
Tag.create(type: 'Mexican')
Tag.create(type: 'Breakfast')
Tag.create(type: 'Brunch')
Tag.create(type: 'Desserts')
Tag.create(type: 'Wine Bar')
Tag.create(type: 'Italian')
Tag.create(type: 'Pizza')
Tag.create(type: 'Gelato')
Tag.create(type: 'Spanish')
Tag.create(type: 'Mediterranean')
Tag.create(type: 'Full Bar')
Tag.create(type: 'Latin American')
Tag.create(type: 'Cocktail Bar')
Tag.create(type: 'Gourmet Hot Dogs')
Tag.create(type: 'Pub Food')

r1.restaurant_tags.create([{tag_id: 1, likeness: 5}, {tag_id: 2, likeness: 4}, {tag_id: 3, likeness: 7}, {tag_id: 4, likeness: 4}, {tag_id: 5, likeness: 8}])
r2.restaurant_tags.create([{tag_id: 7, likeness: 9}, {tag_id: 6, likeness: 6}])
r3.restaurant_tags.create([{tag_id: 8, likeness: 8}, {tag_id: 9, likeness: 9}])
r4.restaurant_tags.create([{tag_id: 10, likeness: 10}, {tag_id: 11, likeness: 7}, {tag_id: 12, likeness: 6}])
r5.restaurant_tags.create([{tag_id: 7, likeness: 9}, {tag_id: 10, likeness: 7}])
r6.restaurant_tags.create([{tag_id: 14, likeness: 8}, {tag_id: 15, likeness: 9}, {tag_id: 3, likeness: 6}, {tag_id: 7, likeness: 7}])
r7.restaurant_tags.create([{tag_id: 16, likeness: 10}, {tag_id: 17, likeness: 8}, {tag_id: 18, likeness: 9}])
r8.restaurant_tags.create([{tag_id: 18, likeness: 10}, {tag_id: 19, likeness: 8}, {tag_id: 20, likeness: 8}])
r9.restaurant_tags.create([{tag_id: 3, likeness: 5}, {tag_id: 21, likeness: 9}, {tag_id: 22, likeness: 7}])
r10.restaurant_tags.create([{tag_id: 3, likeness: 8}, {tag_id: 23, likeness: 10}, {tag_id: 24, likeness: 8}])


User.create(name: 'Judson', username: 'J@gmail.com', password: 'password', admin: true)